eureka:
  instance:
    hostname: localhost
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://localhost:5000/eureka
      searchPaths: main
      
config:
   security:
      oauth:
        client:
           id: facturaApp
           secret: 12345
        jwt:
            key: algun_codigo_secreto_aeiou

microservice:
      payment-service:
        endpoints:
          endpoint:
            uri: http://hbt-payment-service/api/payment/doPayment
      order-service:
        endpoints:
          endpoint:
            uri: http://hbt-order-service/api/order/save
