spring:
  application:
    name: HBT-GATEWAY-SERVICE
  config:
    import=optional:configserver:


  cloud:
    gateway:
      discovery:
        locator:
          enable: true
      routes:
        - id: hbt-cliente-service
          uri: lb://HBT-CLIENTE-SERVICE
          predicates:
            - Path=/hbt/cliente/**
          filters:
            - StripPrefix=2
        - id: hbt-seguridad-service
          uri: lb://HBT-SEGURIDAD-SERVICE
          predicates:
            - Path=/hbt/seguridad/**
          filters:
            - StripPrefix=2
        - id: hbt-upload-service
          uri: lb://HBT-UPLOAD-SERVICE
          predicates:
            - Path=/hbt/upload/**
          filters:
            - StripPrefix=2
            
server:
  port: 8180

logging:
  level:
    org:
      springframework:
        security:
          web: DEBUG
          
management:
  endpoints: 
    web:
      exposure:
        include: "*"

eureka:
  instance:
    hostname: localhost
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://localhost:5000/eureka